
OBJS += image.o

OBJS-$(quickdisk) += qd.o

OBJS-$(apple2) += hfe.o

OBJS-$(shugart) += adf.o
OBJS-$(shugart) += dsk.o
OBJS-$(shugart) += hfe.o
OBJS-$(shugart) += img.o
OBJS-$(shugart) += da.o
OBJS-$(shugart) += dummy.o
OBJS-$(shugart) += mfm.o
