
OBJS += image.o

OBJS-$(quickdisk) += qd.o

OBJS-$(floppy) += adf.o
OBJS-$(floppy) += dsk.o
OBJS-$(floppy) += hfe.o
OBJS-$(floppy) += img.o
OBJS-$(floppy) += da.o
OBJS-$(floppy) += dummy.o
OBJS-$(floppy) += mfm.o
