RPATH = ../src

OBJS += update.o
OBJS += crc.o
OBJS += fpec.o

OBJS += cancellation.o
OBJS += console.o
OBJS += vectors.o
OBJS += fs.o
OBJS += spi.o
OBJS += string.o
OBJS += stm32f10x.o
OBJS += timer.o
OBJS += util.o

SUBDIRS += fatfs
SUBDIRS-$(gotek) += gotek
SUBDIRS-$(touch) += touch
