OBJS += arena.o
OBJS += cancellation.o
OBJS += crc.o
OBJS += vectors.o
OBJS += floppy.o
OBJS += fs.o
OBJS += main.o
OBJS += spi.o
OBJS += string.o
OBJS += stm32f10x.o
OBJS += timer.o
OBJS += util.o

OBJS-$(debug) += console.o

SUBDIRS += fatfs
SUBDIRS += image
SUBDIRS-$(gotek) += gotek
SUBDIRS-$(touch) += touch
