on:
  push:
    tags:
    - 'v*.*'

name: Release

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:

    - uses: actions/checkout@v4

    - name: Set environment variables
      id: vars
      run: |
        echo "ver=$(echo ${{ github.ref }} | sed -e's#.*/v##')" >> $GITHUB_OUTPUT

    - name: Dependency packages (apt)
      run: |
        sudo apt update
        sudo apt -y install git gcc-arm-none-eabi python3-pip srecord stm32flash zip unzip wget

    - name: Dependency packages (pip)
      run: python3 -m pip install --user crcmod intelhex

    - name: Build release
      run: |
        export VER=${{ steps.vars.outputs.ver }}
        make -j4 dist VER=$VER
        mv out/flashfloppy-$VER.zip .

    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.ref }}
        token: ${{ secrets.GITHUB_TOKEN }}
        name: FlashFloppy ${{ steps.vars.outputs.ver }}
        body: "[**Release Notes:**](https://github.com/keirf/flashfloppy/blob/master/RELEASE_NOTES)"
        draft: false
        prerelease: false
        artifacts: flashfloppy-${{ steps.vars.outputs.ver }}.zip
        artifactContentType: application/zip
